In [1]:
import pandas as pd
df = pd.read_csv('Mall_Customers.csv')
print("Shape:", df.shape)
df.head()

Shape: (200, 5)

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [2]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [3]:
print("Duplicate rows:", df.duplicated().sum())
df.drop_duplicates(inplace=True)
print("After removing duplicates:", df.shape)

Duplicate rows: 0
After removing duplicates: (200, 5)

In [9]:
print("Before:", df['Gender'].unique())
df['Gender'] = df['Gender'].str.strip().str.title()
print("After:", df['Gender'].unique())

Before: ['male' 'female']
After: ['Male' 'Female']

In [14]:
print("Before:", df.columns.tolist())
df.columns = ['customer_id', 'gender', 'age', 'annual_income', 'spending_score']
print("After:", df.columns.tolist())

Before: ['customer_id', 'gender', 'age', 'annual_income_k', 'spending_score']
After: ['customer_id', 'gender', 'age', 'annual_income', 'spending_score']

In [15]:
df.dtypes

customer_id        int64
gender            object
age                int64
annual_income      int64
spending_score     int64
dtype: object

In [17]:
print("===== FINAL CLEANED DATASET =====")
print("Shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())
print("\nData types:")
print(df.dtypes)
print("\nSample:")
df.head()

===== FINAL CLEANED DATASET =====
Shape: (200, 5)

Missing values:
customer_id       0
gender            0
age               0
annual_income     0
spending_score    0
dtype: int64

Data types:
customer_id        int64
gender            object
age                int64
annual_income      int64
spending_score     int64
dtype: object

Sample:

   customer_id  gender  age  annual_income  spending_score
0            1    Male   19             15              39
1            2    Male   21             15              81
2            3  Female   20             16               6
3            4  Female   23             16              77
4            5  Female   31             17              40

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     200 non-null    int64
 1   gender          200 non-null    object
 2   age             200 non-null    int64
 3   annual_income   200 non-null    int64
 4   spending_score  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [18]:
df.to_csv("mall_customers_cleaned.csv", index=False)